const bilisim = {
    firstName: "Burak",
    lastName: "ARIKBOĞA",
    prefix: "(Mr.)",
    title: "BT Uzmanı / IT Specialist",
    company: "YAVUZSAN BRAKE DISC & DRUM & PAD",
    email: "bilisim@yavuzsan.com",
    phone: "+90 332 239 22 00",
    website: "www.yavuzsan.com",
    address1: "Konya Organize San. Böl. Kuddusi Cad. No:16",
    address2: "Selçuklu / Konya / TÜRKİYE",
    facebookURL: "https://www.facebook.com/yavuzsanotomotiv",
    linkedinURL: "https://www.linkedin.com/company/yavuzsan-otomoti%CC%87v/",
    twitterURL: "https://x.com/yavuzsan",
    youtubeURL: "https://www.youtube.com/@yavuzsanotomotiv1",
    instagramURL: "https://www.instagram.com/yavuzsanotomotiv",
    lctn_url: "https://maps.app.goo.gl/nDWMqqSnj4Xv8cXSA",
    //pinterestURL: "https://pinterest.com/yavuzsan",
    mobile: "+90 332 239 22 00",

    //pt_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "pt.svg",
    email_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "email.png",
    web_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "web.png",
    phn_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "phn.phn",
    lctn_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "lctn.png",
    fb_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "fb.png",
    ln_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "ln.png",
    x_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "x1.png",
    yt_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "yt.png",
    it_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "it.svg",
    maps_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "maps.png",
    //tt_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "tt.svg",
    banner_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "banner.png",
    logo_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "logo.png",
    line_pic_url: "https://raw.githubusercontent.com/yavuzsanIT/medium-banner/master/src/html/signature/pics/" + "line.png",
};